export const schemaModules = [
  'tenants',
  'groups',
  'users',
  'group_members',
  'auth_identities',
  'invitations',
  'mfa_factors',
  'audit_events',
  'auth_sessions',
  'auth_challenges',
  'sso_domain_claims',
  'admin_access_requests',
  'admin_break_glass_sessions',
  'better_auth_accounts',
  'better_auth_sessions',
  'better_auth_verifications',
  'rbac_roles',
  'rbac_user_roles',
  'workspace_apps',
  'workspace_app_access_grants',
  'workspace_group_app_grants',
  'workspace_app_tool_overrides',
  'workspace_user_preferences',
  'workspace_quota_limits',
  'conversations',
  'runs',
  'run_timeline_events',
  'workspace_uploaded_files',
  'workspace_artifacts',
  'workspace_comments',
  'knowledge_sources',
  'knowledge_source_chunks',
  'tenant_billing_plans',
  'tenant_billing_adjustments',
  'tenant_policy_exceptions',
  'tenant_policy_evaluations',
  'operator_annotations',
  'workflow_definitions',
  'workflow_definition_versions',
  'workflow_definition_permissions',
  'workspace_app_launches',
  'workspace_conversation_shares',
] as const;

export type SchemaModule = (typeof schemaModules)[number];

export * from './schema/index.js';
export * from './runtime.js';
